import { useEffect, useState } from "react";
import { collection, getDocs, query, where, doc, updateDoc } from "firebase/firestore";
import { db } from "../services/firebase";

export default function ReviewHub() {
  const [ideas, setIdeas] = useState([]);
  const [feedback, setFeedback] = useState({});
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  useEffect(() => { getDocs(query(collection(db, "ideas"), where("status", "==", "submitted"))).then((snapshot) => setIdeas(snapshot.docs.map((item) => ({ id: item.id, ...item.data() })))).catch(() => setError("We could not load the review queue.")).finally(() => setLoading(false)); }, []);
  const review = async (id, mentorStatus) => { await updateDoc(doc(db, "ideas", id), { mentorStatus, mentorFeedback: feedback[id] || "", updatedAt: new Date().toISOString() }); setIdeas((current) => current.filter((idea) => idea.id !== id)); };
  if (loading) return <div className="vp-role-page"><div className="vp-role-loading">Loading mentor queue...</div></div>;
  return <div className="vp-role-page"><header className="vp-role-header"><div><span className="vp-role-kicker">Mentor workspace</span><h1>Review ideas with context.</h1><p>Give founders a useful next question, grounded in their evidence and assumptions.</p></div><div className="vp-role-mark">✦</div></header><div className="vp-role-stats"><div><span>Awaiting review</span><strong>{ideas.length}</strong></div><div><span>Evidence to inspect</span><strong>{ideas.filter((idea) => (idea.scores?.evidenceConfidence || 0) < 50).length}</strong></div><div><span>Readiness average</span><strong>{ideas.length ? Math.round(ideas.reduce((sum, idea) => sum + (idea.scores?.overallReadiness || 0), 0) / ideas.length) : 0}</strong></div></div>{error && <p className="vp-role-error">{error}</p>}<section className="vp-role-section"><div className="vp-role-section-heading"><div><span className="vp-role-kicker">Review queue</span><h2>Founder work waiting for your lens</h2></div><span className="vp-role-count">{ideas.length} submissions</span></div>{ideas.length ? <div className="vp-mentor-list">{ideas.map((idea) => <article className="vp-mentor-card" key={idea.id}><div className="vp-mentor-card-heading"><div><span className="vp-partner-stage">Submitted startup</span><h3>{idea.basics?.rawIdea || idea.basics?.title || "Untitled startup"}</h3></div><div className="vp-mentor-score"><strong>{idea.scores?.overallReadiness || 0}</strong><span>readiness</span></div></div><div className="vp-mentor-metrics"><span>Evidence <b>{idea.scores?.evidenceConfidence || 0}%</b></span><span>Focus <b>{idea.workflow?.currentMatrix || "Discovery"}</b></span><span>Assumptions <b>{idea.assumptions?.length || 0}</b></span></div><textarea value={feedback[idea.id] || ""} onChange={(event) => setFeedback((current) => ({ ...current, [idea.id]: event.target.value }))} placeholder="Leave one constructive observation or next question..." rows="3" /><div className="vp-mentor-actions"><button className="vp-role-button is-primary" onClick={() => review(idea.id, "approved")}>Recommend for incubation</button><button className="vp-role-button" onClick={() => review(idea.id, "needs_work")}>Request refinement</button></div></article>)}</div> : <div className="vp-role-empty"><h3>The queue is clear.</h3><p>Submitted founder work will appear here for mentor review.</p></div>}</section></div>;
}